// File: Models/Customer.cs
using System.ComponentModel.DataAnnotations;

namespace EShift.Models
{
    public class Customer
    {
        public int CustomerId { get; set; } // Auto-generated by SQL server

        [Required]
        [StringLength(100)]
        public string Name { get; set; }

        [Required]
        [Phone]
        public string Phone { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}
